name: awx-ee Docker Image on Push to GHCR

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "awx-ee/**"
concurrency:
  group: awx-ee-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
      - name: install ansible-builder
        run: pip install ansible-builder==3.1.1
      - name: build Dockerfile from execution-environment.yml
        working-directory: awx-ee
        run: ansible-builder create --output-filename Dockerfile
      # see https://github.com/actions/upload-artifact#permission-loss
      - name: tar files
        run: tar -cvf build-code.tar -C awx-ee/context .
      - name: upload build context
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: build-code.tar
          archive: false
          retention-days: 1

  build_image_on_push:
    needs: generate_dockerfile
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dbildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@094a0e74897bef119a5a8fc73da781ff1f2274e6 # 8.4.2
    with:
      image_name: "awx-ee"
      context: "./awx-ee/"
      code_source: "artifact"
      image_tag_generation: "ticket_from_branch"
      add_latest_tag: false
      container_registry: "ghcr.io"
      run_trivy_scan: true
      run_clamav_scan: true
      limit-severities-for-sarif: false
      # todo: remove when Helm has been updated (should hopefully to no critical findings)
      fail_on_vulnerabilites: false
