name: awx-ee Docker Image on Push to GHCR

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - "awx-ee/**"
concurrency:
  group: awx-ee-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install ansible-builder
        run: pip install ansible-builder
      - name: build Dockerfile from execution-environment.yml
        working-directory: awx-ee
        run: ansible-builder create --output-filename Dockerfile
      - name: upload build context
        uses: actions/upload-artifact@v4
        with:
          name: build-code
          path: awx-ee/context

  build_image_on_push:
    needs: generate_dockerfile
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@generate-dockerfile
    with:
      image_name: "awx-ee"
      context: "./awx-ee/context"
      image_tag_generation: "specified"
      image_tag: "awx-ee-2.4.2"
      add_latest_tag: false
      container_registry: "ghcr.io"
      run_trivy_scan: true
      run_clamav_scan: true
      limit-severities-for-sarif: false
      code_source: "artifact"
