name: Docker Image generation for crontools Cron Job

on:
  schedule:
    - cron: "0 2 14 * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@f0ea640ef142d04e2f91e1df087f6782585548af # v6.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'test-v'
          tag_template: 'yyyy.mm.i'
          previous_tag: ''
#      - name: Bump version and push tag
#        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # v1.75.0
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
#          CUSTOM_TAG: ${{ steps.generate_release_tag.outputs.next_release_tag }}

