name: Docker Image Trivy Image Vulnerability Scan Cron Job

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read
  packages: read

jobs:
  trivy_image_scan_cron:
    strategy:
      fail-fast: false
      matrix:
        image:
          - infra-tools
          - infra-tools-debian
          - dbcmetrics
          - awx-ee
          - docops
          - cron-tools
          - cron-tools-debian

    uses: dbildungsplattform/dbp-github-workflows/.github/workflows/check-trivy.yaml@4b5c0434f28b537e9199ffebc21f4e6e39cbcdde # 8.4.3
    with:
      image_ref: "ghcr.io/dbildungsplattform/${{ matrix.image }}:latest"
      severity: "CRITICAL,HIGH"
      fail_on_vulnerabilites: true
      ignore-unfixed: true
      limit-severities-for-sarif: false
