name: Docker Image Trivy Image Vulnerability Scan Cron Job

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read
  packages: read

jobs:
  trivy_image_scan_cron:
    strategy:
      fail-fast: false
      matrix:
        image:
          - infra-tools
          - infra-tools-debian
          - dbcmetrics
          - awx-ee
          - docops
          - cron-tools
          - cron-tools-debian

    uses: dbildungsplattform/dbp-github-workflows/.github/workflows/check-trivy.yaml@9512523aad66da194f6734158735c414b17b2e47
    with:
      image_ref: "ghcr.io/dbildungsplattform/${{ matrix.image }}:latest"
