name: Docker Image Trivy Image Vulnerability Scan Cron Job

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  security-events: write
  actions: read
  contents: read
  packages: read

jobs:
  trivy_image_scan_cron:
    strategy:
      fail-fast: false
      matrix:
        image:
          - infra-tools
          - infra-tools-debian
          - dbcmetrics
          - awx-ee
          - docops
          - cron-tools
          - cron-tools-debian

    uses: dbildungsplattform/dbp-github-workflows/.github/workflows/check-trivy.yaml@d3c41733ad624bf26d60979a8fccacfa1c750385
    with:
      image_ref: "ghcr.io/dbildungsplattform/${{ matrix.image }}:latest"
